import express from 'express';
import { createPost } from '../api/createpost';
import { getPostInfo } from '../api/getpostinfo';
import { addLike } from '../api/addlike';
import { removeLike } from '../api/removelike';
import { getAllPostInfo } from '../api/getallpostinfo';
import { createscheduledpost } from '../api/createscheduledpost';
import {save} from '../api/save';
import {unsave} from '../api/unsave';
const router = express.Router();
router.post('/createpost', createPost);
router.post('/getpostinfo', getPostInfo);
router.post('/addlike', addLike);
router.post('/removelike', removeLike);
router.post('/getallpostinfo', getAllPostInfo);
router.post('/createscheduledpost', createscheduledpost);
router.post('/save', save);
router.post('/unsave', unsave);
export default router;